[width="100%",cols="2a,2a,5a",options="header",]

This repository contains scripts and reference files used to upgrading a Fusion deployment.

The upgrade process is described in the Fusion online documentation:
https://doc.lucidworks.com/fusion/2.4/Installation_and_Configuration/Upgrading-Fusion.html[Upgrading Fusion].

* To upgrade to Fusion 2.4.1 from all Fusion 2.1 and 2.2 versions, see:
https://doc.lucidworks.com/fusion/2.4/Installation_and_Configuration/Upgrading_Fusion/upgrade-2_1-to-2_4.html[Upgrade Fusion 2.1 to Fusion 2.4]

* To upgrade to the latest Fusion 2.1 version from Fusion 1.2.3 and later, see
https://doc.lucidworks.com/fusion/2.4/Installation_and_Configuration/Upgrading_Fusion/upgrade-1_2-to-2_1.html[Upgrade Fusion 1.2 to Fusion 2.1]

=== Upgrade scripts

* The `src` directory is used to upgrade Fusion 2.1 to Fusion 2.4.
It contains a Python program which rewrites Fusion datasource configurations automatically:
https://github.com/lucidworks/fusion-upgrade-scripts/tree/master/src[upgrade-ds-2.1-to-2.4.py]

* The `bin` directory is used to upgrade Fusion 1.2 to Fusion 2.1.
It contains two utilities:

** Python script 
https://github.com/lucidworks/fusion-upgrade-scripts/tree/master/bin[download_upload_ds_pipelines.py]
which rewrites Fusion datasource and pipeline configurations in order to encode any stored passwords needed for those datasources.
This script uses packages http://docs.python-requests.org/en/latest/user/install/#install[requests] and https://kazoo.readthedocs.org/en/latest/install.html[kazoo],
which are an HTTP request handler and ZooKeeper client, respectively.
If for some reason, the user running the upgrade scripts doesn't have install permissions, use Python's http://docs.python-guide.org/en/latest/dev/virtualenvs/[virtualenv]. +

** Java program which rewrites pre-2.1 Fusion crawldb files to the data format introduced in Fusion 2.1:
https://github.com/lucidworks/fusion-upgrade-scripts/tree/master/bin[com.lucidworks.fusion-crawldb-migrator-0.1.0.jar]

=== Reference filesets

To facilitate the task of identifying changes made run scrips and their configuration files,
the directory `reference-files` contains copies of the contents of these directories for all Fusion releases.


