Instructions: Upgrade to latest Fusion 1.2
------------------------------------------

This set of upgrade instructions is for

* FUSION-CURRENT:  Fusion 1.2 version at 1.2.3 or higher
* FUSION-NEW: the latest version of Fusion 1.2

INSTALL-DIR refers to the parent directory of the FUSION-CURRENT deployment or a staging directory
which contains a copy of the FUSION-CURRENT installation.
All commands in the upgrade instruction set are run from this directory.


Upgrade Process Overview
------------------------

To upgrade while leaving FUSION-CURRENT deployment in place, you must set up parallel current and new Fusion installs in the INSTALL-DIR.
If either the local ZooKeeper or Solr installation is being used, this data must be copied over from the current to the new installation.


* link:#step-1[Download, unpack FUSION-NEW]

* link:#step-2[Copy embedded ZooKeeper and/or Solr]
If Fusion is using either the ZooKeeper or the Solr installation included with the Fusion distribution or both,
the ZooKeeper and Solr data must be copied from FUSION-CURRENT to FUSION-NEW.

* link:#step-3[Save custom settings in Fusion configuration files and run scripts.] Preserve customizations, including settings for external ZooKeeper and Solr.

* link:#step-4[Copy crawldb.] Preserve information about what has been indexed by Fusion datasources.

* link:#step-5[Copy JDBC driver jarfiles.] Only required for JDBC datasources.



[[step-1]]
Download, unpack FUSION-NEW
^^^^^^^^^^^^^^^^^^^^^^^^^^^

`cd` to directory INSTALL-DIR. The disk partition this directory is on must have at least as much free disk space as the size of the FUSION-CURRENT directory.
On a *nix system, the following commands can be used:

* `du -sh fusion` - total size of FUSION-CURRENT.
* `df -kH` - amount of free space on all file-systems.

Download or copy the Fusion distribution for FUSION-NEW into INSTALL-DIR.
The latest Fusion distribution is available from https://lucidworks.com/products/fusion/download/get-started/
It is distributed as a gzipped tar file or as a compressed zip file.

Create a new directory named "fusion-new" and unpack the contents of the distribution here.
For example, to upgrade to Fusion 1.2.7, the archive file is named "fusion-1.2.7.tar.gz".
The default tar -xf command would unpack this into a directory named "fusion"
which would overwrite parts of the FUSION-CURRENT installation.
To avoid this, run the following commands:

------------------------------------------
> mkdir fusion-new
> tar -C fusion-new --strip-components=1 -xf fusion-1.2.7.tar.gz
------------------------------------------

If you are working on a Windows machine, the zipfile unzips into a folder named "fusion-1.2.7" which contains a folder named "fusion".
Rename "fusion" to "fusion-new" and moved it into folder INSTALL-DIR.

[[step-2]]
Copy embedded ZooKeeper and/or Solr (as needed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Fusion distribution includes both a ZooKeeper and Solr install.
This "out of the box" configuration ("OOTB") is intended mainly for development purposes.
In a production an external ZooKeeper cluster should be used,
and an external Solr cluster is likely to be used.

If you are running the OOTB Fusion, then you must copy over both the ZooKeeper configuration and all Solr data.
If you are using an external ZooKeeper but using Fusion's local Solr install, you must copy over all Solr data.

To copy the ZooKeeper configuration:

------------------------------------------
> mkdir -p fusion-new/data/zookeeper
> cp -R fusion/solr/zoo_data/* fusion-new/data/zookeeper
------------------------------------------

To check your work: compare the directories `fusion/solr/zoo_data/` and `fusion-new/data/zookeeper`
using the `diff` command.  This command succeeds silently when the contents are the same.

------------------------------------------
> diff -r fusion/solr/zoo_data fusion-new/data/zookeeper
------------------------------------------

To copy the Solr data:

------------------------------------------
> find fusion/solr -maxdepth 1 -mindepth 1 | grep -v -E "zoo*" | while read f ; do cp -R $f fusion-new/data/solr/; done
------------------------------------------

If the Solr collections are very large this may take a while.

You can use the `diff` command to check your work.
The copy command excluded ZooKeeper config data, therefore
you should see the following output:

------------------------------------------
> diff -r fusion/solr fusion-new/data/solr
Only in fusion-new/data/solr: configsets
Only in fusion/solr: zoo.cfg
Only in fusion/solr: zoo_data
------------------------------------------


[[step-3]]
Save custom settings in Fusion configuration files and run scripts
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Fusion configuration files define environment variables used in the Fusion run scripts.
The Fusion run scripts start and stop Fusion services.
If you are using an external ZooKeeper, or have changed memory limits on any Fusion services,
these files will have been changed.

In Fusion 1.2, the "fusion/bin" directory contains configuration files and run scripts for all Fusion services:

------------------------------------
README.txt
api
api.cmd
common.sh
config.cmd
config.sh
connectors
connectors.cmd
fusion
fusion.cmd
oom.sh
solr
solr.cmd
spark-master
spark-master.cmd
spark-worker
spark-worker.cmd
ui
ui.cmd
------------------------------------

If these files have been customized for your installation, you must identify those changes and then *edit* the files in "fusion-new" accordingly.
New changes and optimizations may have been added to these files in later releases.
These changes will be lost by replacing the new with the old by a copy command,
thus a by-hand edit is needed to properly carry over customizations.

To facilitate the task of identifying changes made to the current installation,
the fusion-upgrade-scripts repository contains a directory "reference-files" which
contains bin directories for Fusion releases 1.2.3, 1.2.4, and 1.2.6 named "bin-1.2.3", "bin-1.2.4", and "bin-1.2.6".
To identify changes, use the *nix `diff` command with the `-r` flag, e.g. if FUSION-CURRENT is 1.2.3, then the command is:

------------------------------------
> diff -r INSTALL-DIR/fusion/bin FUSION-UPGRADE-SCRIPTS/reference-files/bin-1.2.3
------------------------------------

[[step-4]]

Copy the crawldb
^^^^^^^^^^^^^^^^

The Fusion "crawldb" records the results of running datasource jobs.  This information must be copied from FUSION-CURRENT to FUSION-NEW.

Copy the Fusion "crawldb" directory:

------------------------------------
> cp -R fusion/data/connectors/crawldb fusion-new/data/connectors/
------------------------------------


[[step-5]]
Copy JDBC driver jarfiles
^^^^^^^^^^^^^^^^^^^^^^^^^

The jarfiles for any JDBC drivers used by a JDBC datasource are found in directory:  "fusion/data/connectors/lucid.jdbc"
Copy the contents of this directory over to the "fusion-new" directory:

------------------------------------
> cp -R fusion/data/connectors/lucid.jdbc fusion-new/data/connectors/
------------------------------------


This completes the upgrade process.

At this point, you should validate the FUSION-NEW, per instructions in the link:README.asciidoc.
Once validated, you can archive and/or delete the directory INSTALL-DIR/fusion
and then rename INSTALL-DIR/fusion-new to INSTALL-DIR/fusion.
