DATASOURCES_NODE = "lucid/connectors/datasources"
MIGRATORS_FILE = "migrators.json"

DEFAULT_EMPTY = ""
PROPERTIES = "properties"
ENABLE_SECURITY_TRIMMING = "enable_security_trimming"

AD_URL = "ad_url"
AD_PRINCIPAL = "ad_user_principal_name"
AD_CREDENTIALS = "ad_credentials"
AD_USER_FILTER = "ad_user_filter"
AD_GROUP_FILTER = "ad_group_filter"
AD_USER_BASE_DN = "ad_user_base_dn"
AD_GROUP_BASE_DN = "ad_group_base_dn"
AD_CONTEXT_FACTORY = "ad_context_factory"
AD_SECURITY_AUTH = "ad_security_authentication"
AD_CACHE_GROUPS = "ad_cache_groups"
AD_READ_TOKEN_GROUPS = "ad_read_token_groups"
AD_READ_TIMEOUT = "ad_read_timeout"
AD_CONNECT_TIMEOUT = "ad_connect_timeout"
AD_REFERRAL = "ad_referral"
MAX_CACHE_SIZE = "max_cache_size"
CACHE_EXPIRATION_TIME = "cache_element_expiration_time"
ENABLE_SIDS_CACHE = "enable_SIDs_cache"

SPLIT_CSV = "splitCSV"
CSV_FORMAT = "csvFormat"
CSV_WITH_HEADER = "csvWithHeader"
CSV_ID_COLUMN = "csvIDColumn"
CSV_DELIMETER_OVERRIDE = "csvDelimeterOverride"
CSV_COMMENT_OVERRIDE = "csvCommentOverride"
CSV_CHARACTER_SET_OVERRIDE = "csvCharacterSetOverride"

LDAP_HOST = "f.ldap_host"
LDAP_PORT = "f.ldap_port"
LDAP_USE_SSL = "f.ldap_use_ssl"
LDAP_READ_GROUPS_TYPE = "f.ldap_read_groups_type"
LDAP_SEARCH_BASE = "f.ldap_search_base"
LDAP_SECURITY_FILTER_CACHE = "f.security_filter_cache"
F_CACHE_EXPIRATION_TIME = "f.cache_expiration_time"
CACHE_MAX_SIZE = "f.cache_max_size"

OBJECTS_TO_CRAWL = "objects_to_crawl"

DEFAULT = "default"
COMMA = ","
NUMBER = "#"
UTF_8 = "UTF-8"
TOKEN_GROUPS = "TOKEN_GROUPS"
LDAP_CTX_FACTORY = "com.sun.jndi.ldap.LdapCtxFactory"
SIMPLE = "simple"
FOLLOW = "follow"

RETAIN_OUT_LINKS = "retainOutlinks"
REEVALUATE_CRAWL_DB_ON_START = "reevaluateCrawlDBOnStart"
TRACK_EMBEDDED_IDS = "trackEmbeddedIDs"
ALIAS_EXPIRATION = "aliasExpiration"
FETCH_DELAY_MS_PER_HOST = "fetchDelayMSPerHost"
LEGAL_URI_SCHEMES_PROP = "legalURISchemes"

# Salesforce 1.2.x properties
SALESFORCE_FILESYSTEM_PROPERTIES_PREFIX = "properties.f.fs"