MIGRATORS_FILE = "migrators.json"

DEFAULT_EMPTY = ""
PROPERTIES = "properties"
ENABLE_SECURITY_TRIMMING = "enable_security_trimming"

AD_URL = "ad_url"
AD_PRINCIPAL = "ad_user_principal_name"
AD_CREDENTIALS = "ad_credentials"
AD_USER_FILTER = "ad_user_filter"
AD_GROUP_FILTER = "ad_group_filter"
AD_USER_BASE_DN = "ad_user_base_dn"
AD_GROUP_BASE_DN = "ad_group_base_dn"
AD_CONTEXT_FACTORY = "ad_context_factory"
AD_SECURITY_AUTH = "ad_security_authentication"
AD_CACHE_GROUPS = "ad_cache_groups"
AD_READ_TOKEN_GROUPS = "ad_read_token_groups"
AD_READ_TIMEOUT = "ad_read_timeout"
AD_CONNECT_TIMEOUT = "ad_connect_timeout"
AD_REFERRAL = "ad_referral"
MAX_CACHE_SIZE = "max_cache_size"
CACHE_EXPIRATION_TIME = "cache_element_expiration_time"
ENABLE_SIDS_CACHE = "enable_SIDs_cache"

SPLIT_CSV = "splitCSV"
CSV_FORMAT = "csvFormat"
CSV_WITH_HEADER = "csvWithHeader"
CSV_ID_COLUMN = "csvIDColumn"
CSV_DELIMETER_OVERRIDE = "csvDelimeterOverride"
CSV_COMMENT_OVERRIDE = "csvCommentOverride"
CSV_CHARACTER_SET_OVERRIDE = "csvCharacterSetOverride"

LDAP_HOST = "f.ldap_host"
LDAP_PORT = "f.ldap_port"
LDAP_USE_SSL = "f.ldap_use_ssl"
LDAP_READ_GROUPS_TYPE = "f.ldap_read_groups_type"
LDAP_SEARCH_BASE = "f.ldap_search_base"
LDAP_SECURITY_FILTER_CACHE = "f.security_filter_cache"
F_CACHE_EXPIRATION_TIME = "f.cache_expiration_time"
CACHE_MAX_SIZE = "f.cache_max_size"

OBJECTS_TO_CRAWL = "objects_to_crawl"

DEFAULT = "default"
COMMA = ","
NUMBER = "#"
UTF_8 = "UTF-8"
TOKEN_GROUPS = "TOKEN_GROUPS"
LDAP_CTX_FACTORY = "com.sun.jndi.ldap.LdapCtxFactory"
SIMPLE = "simple"
FOLLOW = "follow"

RETAIN_OUT_LINKS = "retainOutlinks"
REEVALUATE_CRAWL_DB_ON_START = "reevaluateCrawlDBOnStart"
TRACK_EMBEDDED_IDS = "trackEmbeddedIDs"
ALIAS_EXPIRATION = "aliasExpiration"
FETCH_DELAY_MS_PER_HOST = "fetchDelayMSPerHost"
LEGAL_URI_SCHEMES_PROP = "legalURISchemes"

# Salesforce 1.2.x properties
SALESFORCE_FILESYSTEM_PROPERTIES_PREFIX = "properties.f.fs"

COLLECTION = "collection"

F_GITHUB_TYPE = "f.github_type"
LIST_HOSTS = "list_hosts"
LIST_CREDENTIALS = "list_credentials"
HOST = "host"
PORT = "port"
COLLECTIONS = "collections"
USERNAME = "username"
PASSWORD = "password"
DATABASE = "database"

DASH = "-"
DASH_D = "-D"
DASH_I = "-i"
DASH_CLS = "-cls"
EQUAL = "="
JOB_JAR_ARGS = "job_jar_args"
COMMIT_CLOSE = "lww.commit.on.close"
PIPELINE_URI = "pipeline.uri"
HADOOP_INPUT = "hadoop_input"
HADOOP_MAPPER = "hadoop_mapper"
MAPPER_ARGS = "mapper_args"
RUN_KINIT = "run_kinit"
KINIT_USER = "kinit_user"
KINIT_CACHE = "kinit_cache"
KINIT_KEYTAB = "kinit_keytab"
KINIT_PRINCIPAL = "kinit_principal"
DIRECTORY_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.DirectoryIngestMapper"
CSV_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.CSVIngestMapper"
GROK_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.GrokIngestMapper"
REGEX_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.RegexIngestMapper"
SEQUENCE_FILE_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.SequenceFileIngestMapper"
SOLR_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.SolrXMLIngestMapper"
WARC_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.WarcIngestMapper"
ZIP_INGEST_MAPPER = "com.lucidworks.hadoop.ingest.ZipIngestMapper"
DIRECTORY = "DIRECTORY"
CSV = "CSV"
GROK = "GROK"
REGEX = "REGEX"
SEQUENCE_FILE = "SEQUENCE_FILE"
SOLR_XML = "SOLR_XML"
WARC = "WARC"
ZIP = "ZIP"

LUCID_ANDA = "lucid.anda"
LUCID_FS = "lucid.fs"

TYPE = "type"

AZURE = "azure"
SMB = "smb"
S3 = "s3"
FTP = "ftp"
COUCHBASE = "couchbase"
JDBC = "jdbc"
SHAREPOINT = "sharepoint"
GITHUB = "github"
DROPBOX = "dropbox"
ZENDESK = "zendesk"
TWITTER_SEARCH = "twitter_search"
TWITTER_STREAM = "twitter_stream"
DRUPAL = "drupal"
JIRA = "jira"
GOOGLEDRIVE = "googledrive"
SUBVERSION = "subversion"
SALESFORCE = "salesforce"
SERVICE_NOW = "serviceNow"
SLACK = "slack"
ALFRESCO = "alfresco"
BOX = "box"
JIVE = "jive"
FILE = "file"
WEB = "web"
HDFS = "hdfs"
HADOOP = "hadoop"
FILE_UPLOAD = "fileupload"

CONNECTOR = "connector"
ID = "id"
PARSER_ID = "parserId"
DELIMITER = "delimiter"
COMMENT = "comment"
HAS_HEADER = "hasHeaders"
HEADERS = "headers"
CHARSET = "charset"
DETECT = "detect"
MARK = "mark"
ERROR_HANDLING = "errorHandling"
COMMENT_HANDLING = "commentHandling"
CSV_DELIMITER = "csv_delimiter"
HEADER_LINE = "header_line"
FIELD_NAMES = "field_names"
SPLITTER = "splitter"
SPLIT_ARCHIVES = "splitArchives"